### ISSUE TITLE
Unnecessary class components

### ISSUE THREAD

**Issue by oliverjam** [fac-15/CHC-React#21]
I understand it's probably just copy/paste duplication that you haven't got around to fixing, but I thought I'd point it out anyway.

Your only stateful component is the App, so it would be simpler for all the others to be function components that render JSX based on their props.

**Comment by helenzhou6** [comment]
Note this is the same issue as: https://github.com/fac-15/CHC-React/issues/18

**Comment by oliverjam** [comment]
Sorry for the duplicate!
